resource_types:
  - name: ccache
    type: docker-image
    source:
      repository: yolo/ccache_resource

  - name: cmake
    type: docker-image
    source:
      repository: yolo/cmake_resource

  - name: python
    type: docker-image
    source:
      repository: yolo/python_resource

  - name: gcc_source
    type: docker-image
    source:
      repository: yolo/gcc_source_resource

resources:
  - name: gcc_source
    type: gcc_source

  - name: cmake
    type: cmake

  - name: ccache
    type: ccache

  - name: static_python
    type: python

  - name: ninja
    type: github-release
    source:
      user: ninja-build
      repository: ninja

  - name: gcc_src
    type: git
    source:
      uri: https://github.com/d/kickass-lovelace
      paths:
        - gcc
      branch: develop

  - name: gcc4_centos5
    type: s3
    __ignored: &bucket_config
      bucket: {{bucket}}
      access_key_id: {{s3_access_key}}
      secret_access_key: {{s3_secret_key}}
    source:
      versioned_file: gcc/gcc4/centos5/gcc.tar.xz
      <<: *bucket_config

  - name: gcc5_centos5
    type: s3
    source:
      versioned_file: gcc/gcc5/centos5/gcc.tar.xz
      <<: *bucket_config

  - name: gcc6_centos5
    type: s3
    source:
      versioned_file: gcc/gcc6/centos5/gcc.tar.xz
      <<: *bucket_config

  - name: gcc4_centos6
    type: s3
    source:
      versioned_file: gcc/gcc4/centos6/gcc.tar.xz
      <<: *bucket_config

  - name: gcc6_centos6
    type: s3
    source:
      versioned_file: gcc/gcc6/centos6/gcc.tar.xz
      <<: *bucket_config

  - name: orcadev_src
    type: git
    source:
      uri: https://github.com/d/kickass-lovelace
      paths:
        - orcadev/centos5
      branch: develop

  - name: orcadev
    type: docker-image
    __ignored: &dockerhub_credentials
      username: {{docker_hub_username}}
      password: {{docker_hub_password}}
    source:
      repository: yolo/orcadev
      tag: centos5
      <<: *dockerhub_credentials

  - name: orcadev_rc
    type: docker-image
    source:
      repository: yolo/orcadev
      tag: centos5_rc
      <<: *dockerhub_credentials

  - name: orcadev_gcc4_src
    type: git
    source:
      uri: https://github.com/d/kickass-lovelace
      paths:
        - orcadev/gcc4
      branch: develop

  - name: orcadev_gcc4_rc
    type: docker-image
    source:
      repository: yolo/orcadev
      tag: gcc4_rc
      <<: *dockerhub_credentials

  - name: orcadev_gcc4
    type: docker-image
    source:
      repository: yolo/orcadev
      tag: gcc4
      <<: *dockerhub_credentials

  - name: gpdbdev_src
    type: git
    source:
      uri: https://github.com/d/kickass-lovelace
      paths:
        - gpdbdev/centos6
      branch: develop

  - name: gpdbdev
    type: docker-image
    source:
      repository: yolo/gpdbdev
      tag: centos6
      <<: *dockerhub_credentials

  - name: gpdbdev_rc
    type: docker-image
    source:
      repository: yolo/gpdbdev
      tag: centos6_rc
      <<: *dockerhub_credentials

  - name: centos6
    type: docker-image
    source:
      repository: centos
      tag: "6"

  - name: centos5
    type: docker-image
    source:
      repository: centos
      tag: "5"

jobs:
  - name: orcadev
    plan:
      - aggregate:
        - get: centos5
          params:
            save: true
        - get: src
          resource: orcadev_src
          trigger: true
      - put: orcadev_rc
        params:
          cache: true
          load_base: centos5
          build: src/orcadev/centos5
        get_params:
          save: true
      - task: test
        image: orcadev_rc
        file: src/orcadev/centos5/test.yml
      - put: orcadev
        params:
          load: orcadev_rc

  - name: gpdbdev
    plan:
      - aggregate:
        - get: centos6
          params:
            save: true
        - get: src
          resource: gpdbdev_src
          trigger: true
      - put: gpdbdev_rc
        params:
          build: src/gpdbdev/centos6
          load_base: centos6
          cache: true
        get_params:
          save: true
      - task: test
        image: gpdbdev_rc
        file: src/gpdbdev/centos6/test.yml
      - put: gpdbdev
        params:
          load: gpdbdev_rc

  - name: gcc4_centos5
    plan:
      - aggregate:
        - get: orcadev
        - get: gcc_source
          version:
            version: "4.9.4"
        - get: src
          resource: gcc_src
          trigger: true
      - task: compile
        image: orcadev
        file: src/gcc/compile.yml
      - put: gcc4_centos5
        params:
          file: gcc/gcc.tar.xz

  - name: gcc5_centos5
    plan:
      - aggregate:
        - get: orcadev
        - get: gcc_source
          version:
            version: "5.4.0"
        - get: src
          resource: gcc_src
          trigger: true
      - task: compile
        image: orcadev
        file: src/gcc/compile.yml
      - put: gcc5_centos5
        params:
          file: gcc/gcc.tar.xz

  - name: gcc6_centos5
    plan:
      - aggregate:
        - get: orcadev
        - get: gcc_source
          version:
            version: "6.2.0"
        - get: src
          resource: gcc_src
          trigger: true
      - task: compile
        image: orcadev
        file: src/gcc/compile.yml
      - put: gcc6_centos5
        params:
          file: gcc/gcc.tar.xz

  - name: gcc4_centos6
    plan:
      - aggregate:
        - get: gpdbdev
        - get: gcc_source
          version:
            version: "4.9.4"
        - get: src
          resource: gcc_src
          trigger: true
      - task: compile
        image: gpdbdev
        file: src/gcc/compile.yml
      - put: gcc4_centos6
        params:
          file: gcc/gcc.tar.xz

  - name: gcc6_centos6
    plan:
      - aggregate:
        - get: gpdbdev
        - get: gcc_source
          version:
            version: "6.2.0"
        - get: src
          resource: gcc_src
          trigger: true
      - task: compile
        image: gpdbdev
        file: src/gcc/compile.yml
      - put: gcc6_centos6
        params:
          file: gcc/gcc.tar.xz

  - name: orcadev_gcc4
    plan:
      - aggregate:
        - get: centos5
          params:
            save: true
        - get: cmake
        - get: ccache
        - get: ninja
          version:
            tag: "v1.7.1"
        - get: python
          resource: static_python
        - get: src
          resource: orcadev_gcc4_src
          trigger: true
        - get: gcc4
          resource: gcc4_centos5
          passed:
            - gcc4_centos5
      - task: prepare
        file: src/orcadev/gcc4/prepare.yml
      - put: orcadev_gcc4_rc
        params:
          cache: true
          load_base: centos5
          build: prepared
        get_params:
          save: true
      - task: test
        image: orcadev_gcc4_rc
        file: src/orcadev/gcc4/test.yml
      - put: orcadev_gcc4
        params:
          load: orcadev_gcc4_rc
