resource_types:
  - name: gcc_source
    type: docker-image
    source:
      repository: yolo/gcc_source_resource

resources:
  - name: gcc_source
    type: gcc_source

  - name: gcc_src
    type: git
    source:
      uri: https://github.com/d/kickass-lovelace
      paths:
        - gcc
      branch: develop

  - name: gcc4_centos5
    type: s3
    source:
      bucket: {{bucket}}
      versioned_file: gcc/gcc4_centos5.tar.gz
      access_key_id: {{s3_access_key}}
      secret_access_key: {{s3_secret_key}}

  - name: orcadev_src
    type: git
    source:
      uri: https://github.com/d/kickass-lovelace
      paths:
        - orcadev/centos5
      branch: develop

  - name: orcadev
    type: docker-image
    __ignored: &dockerhub_credentials
      username: {{docker_hub_username}}
      password: {{docker_hub_password}}
    source:
      repository: yolo/orcadev
      tag: centos5
      <<: *dockerhub_credentials

  - name: gpdbdev_src
    type: git
    source:
      uri: https://github.com/d/kickass-lovelace
      paths:
        - gpdbdev/centos6
      branch: develop

  - name: gpdbdev
    type: docker-image
    source:
      repository: yolo/gpdbdev
      tag: centos6
      <<: *dockerhub_credentials

  - name: centos6
    type: docker-image
    source:
      repository: centos
      tag: "6"

  - name: centos5
    type: docker-image
    source:
      repository: centos
      tag: "5"

jobs:
  - name: orcadev
    plan:
      - aggregate:
        - get: centos5
          params:
            save: true
        - get: src
          resource: orcadev_src
          trigger: true
      - put: orcadev
        params:
          cache: true
          load_base: centos5
          build: src/orcadev/centos5
      - task: test
        image: orcadev
        file: src/orcadev/centos5/test.yml

  - name: gpdbdev
    plan:
      - aggregate:
        - get: centos6
          params:
            save: true
        - get: src
          resource: gpdbdev_src
          trigger: true
      - put: gpdbdev
        params:
          build: src/gpdbdev/centos6
          load_base: centos6
          cache: true
      - task: test
        image: gpdbdev
        file: src/gpdbdev/centos6/test.yml

  - name: gcc4_centos5
    plan:
      - aggregate:
        - get: gcc_source
          version:
            version: "4.9.4"
        - get: src
          resource: gcc_src
          trigger: true
      - task: compile
        file: src/gcc/compile.yml
      - put: gcc4_centos5
        params:
          file: gcc/gcc.tar.gz
