#!/bin/bash

set -e -u -o pipefail
set -x

exec 3>&1
exec >&2

_main() {
	local destination
	destination=$1

	# gpg: key 18ADD4FF: public key "Benjamin Peterson <benjamin@python.org>" imported
	gpg --keyserver ha.pool.sks-keyservers.net --recv-keys C01E1CAD5EA2C4F0B8E3571504C367C218ADD4FF

	local PYTHON_VERSION=2.7.12
	curl -fSL "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tgz" -o python.tgz
	curl -fSL "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tgz.asc" -o python.tgz.asc
	gpg --batch --verify python.tgz.asc python.tgz
	mkdir -p /usr/src/python
	tar -xC /usr/src/python --strip-components=1 -f python.tgz
	cd /usr/src/python
	./configure --enable-unicode=ucs4 --prefix="${destination}"
	make -j8 install

	curl -fSL 'https://bootstrap.pypa.io/get-pip.py' | "${destination}"/bin/python2
	"${destination}"/bin/pip install --no-cache-dir --upgrade pip
	find /usr/local -depth \
		\( \
		    \( -type d -a -name test -o -name tests \) \
		    -o \
		    \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
		\) -exec rm -rf '{}' +

	cat >&3 <<-METADATA
	{"version": {"version": "${PYTHON_VERSION}"}}
	METADATA
}

_main "$@"
