#!/bin/bash

set -e -u -o pipefail
set -x

exec 3>&1
exec >&2

_main() {
	local destination
	destination=$1

	gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 7BFB4EDA

	local VERSION=3.6.1
	local INSTALLER=cmake-${VERSION}-Linux-x86_64.sh
	local CHECKSUM=cmake-${VERSION}-SHA-256.txt
	wget http://cmake.org/files/v${VERSION%.*}/{${INSTALLER},${CHECKSUM}{,.asc}}
	(
		gpg --verify ${CHECKSUM}{.asc,}
		fgrep ${INSTALLER} ${CHECKSUM} | sha256sum --check -
	)
	sh ./${INSTALLER} --prefix=${destination} --exclude-subdir

	cat >&3 <<-METADATA
	{
		"version": {
			"version": "3.6.1"
		}
	}
	METADATA
}

_main "$@"
